### ISSUE TITLE
Write data in canonical form to avoid spurious changes

### ISSUE THREAD

**Issue by xogeny** [modelica/fmi-xc-scripts#8]
Every time we update the file-based database, the entities will get re-ordered.  We should decide on some canonical order (and formatting) so that identical data always looks identical on the file system.

**Comment by andreas-junghanns** [comment]
I used Python's sorted() function to do just that. I left the details to those smart guys ;)

**Comment by xogeny** [comment]
Yes, that works if the sort comparison function never ranks two entities as equal.  So the trick then becomes getting the criteria correct.

**Comment by xogeny** [comment]
Fixed in my current branch.
